extract ensure_agent, that ensures agent is running

diff --git a/bin/ckssh b/bin/ckssh
--- a/bin/ckssh
+++ b/bin/ckssh
@@ -121,6 +121,25 @@ extract_keyfiles() {
     done
 }
 
+ensure_agent() {
+    local compartment="$1"
+    local ssh_command="$2"
+
+    #### Setup environment
+    ssh_add="${ssh_command:-ssh}-add"
+    mkdir -m 0700 -p "$(dirname "$SSH_AUTH_SOCK")"
+    export SSH_AUTH_SOCK="$ckssh_socket_dir/$compartment"
+
+    #### Start agent if not already running
+    e="$("$ssh_add" -l >/dev/null 2>&1; echo $?)"
+    case $e in
+        0) : ;;     # Running with identities
+        1) : ;;     # No identities
+        2) eval "$(ssh-agent -a "$SSH_AUTH_SOCK" || echo false)" >/dev/null;;
+        *) err "Unknown error from $ssh_add -l: $e";;
+    esac
+}
+
 ckssh_add() {
     local compartment="$1"
     shift || err "Usage: $(basename $0) <compartment-name>"
@@ -156,19 +175,7 @@ ckssh_add() {
         extract_keyfiles keyfiles config
     fi
 
-    #### Setup environment
-    ssh_add="${ssh_command:-ssh}-add"
-    mkdir -m 0700 -p "$(dirname "$SSH_AUTH_SOCK")"
-    export SSH_AUTH_SOCK="$ckssh_socket_dir/$compartment"
-
-    #### Start agent if not already running
-    e="$("$ssh_add" -l >/dev/null 2>&1; echo $?)"
-    case $e in
-        0) : ;;     # Running with identities
-        1) : ;;     # No identities
-        2) eval "$(ssh-agent -a "$SSH_AUTH_SOCK" || echo false)" >/dev/null;;
-        *) err "Unknown error from $ssh_add -l: $e";;
-    esac
+    ensure_agent "$compartment" "$ssh_command"
 
     #### Add keys if none loaded or given on command line
     if $given_keyfile_args \
