Test: Improve Bash error checks and failures
(Tests were broken before this change; this is the start of fixing them.)

Set -u and -E. Change trap from anything to just ERR, so we need not
unset the trap when done, and make it catch internal errors only.
Failures are now signaled with the fail() function.

We can clean with -c as well as -C now.

diff --git a/Test b/Test
--- a/Test
+++ b/Test
@@ -1,16 +1,16 @@
 #!/usr/bin/env bash
-set -e -o pipefail
+set -Eeuo pipefail
+trap 'ec=$?; echo 1>&2 "INTERNAL ERROR: ec=$ec line=$LINENO cmd=$BASH_COMMAND";
+      exit $ec;' ERR
 
-trap 'echo FAILED!; exit 1' 0
-
-fail() { echo 1>&2 'FAILURE:' "$@"; exit 1; }
+fail() { ec=$?; echo "FAILED ($ec)" "$@"; exit $ec; }
 
 basedir=$(cd "$(dirname "$0")" && pwd -P)
 cd "$basedir"
-[[ $1 = -C ]] && { shift; git clean -fdX; }
+[[ ${1:-} = -[cC] ]] && { shift; git clean -fdX; }
 . ./pactivate -q
 
-PYTHONPATH=bin pytest -qq "$@" t/unit.py t/functional.py
+PYTHONPATH=bin pytest -qq "$@" t/unit.py t/functional.py || fail pytest
 
 #   Simple form when you expect no messages to stdout
 eval $(bin/ckssh.py bash-init)
@@ -36,5 +36,4 @@ actual=$(
     "ckset: expected $_compartment, actual '$actual'"
 [[ $exitcode -eq 2 ]] || fail "ckset: expected \$?=2, actual \$?=$exitcode"
 
-trap '' 0
 echo OK
